[package]
name = "ftp"
version = "0.0.8"
authors = ["Matt McCoy <mattnenterprise@yahoo.com>"]
documentation = "http://mattnenterprise.github.io/rust-ftp"
repository = "https://github.com/mattnenterprise/rust-ftp"
description = "FTP client for Rust"
readme = "README.md"
license = "Apache-2.0/MIT"
keywords = ["ftp"]

[lib]
name ="ftp"
path = "src/lib.rs"

[features]
# Enable support of FTPS which requires openssl
secure = ["openssl"]

# Add debug output (to STDOUT) of commands sent to the server
# and lines read from the server
debug_print = []

[dependencies]
lazy_static = "0.1"
regex = "0.1"
chrono = "0.2"

[dependencies.openssl]
version = "0.7"
optional = true
